- name: "Test Ansible ENV"
  hosts: localhost
  tasks:
    - name: Set default value to Undefined, if the variable is not defined
      debug:
        msg: "AZURE_RESOURCEGROUP: {{ lookup('env', 'AZURE_RESOURCEGROUP') }} is the vars."
